key = "Yg&tc%DEuh6%Zc^8"
iv = "6oyZDr22E3ychjM%"

#THIS CODE CREATE BY @JOBAYAR_AHME
#THIS CODE CREATE BY @JOBAYAR_AHME
#THIS CODE CREATE BY @JOBAYAR_AHME
#THIS CODE CREATE BY @JOBAYAR_AHME
#THIS CODE CREATE BY @JOBAYAR_AHME
#THIS CODE CREATE BY @JOBAYAR_AHME